DeltaDashboard/Controllers/DeltaDashboardController.cs
using DeltaDashboardBL.Manager;
using DeltaDashboardCommon.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeIsMoney.Helpers;

namespace DeltaDashboard.Controllers
{
    [Authorization]
    public class DeltaDashboardController : Controller
    {
        // GET: DeltaDashboard
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult DeltaIndex()
        {
            User user = new UserManager().GetUserByUserName(Session["UserName"].ToString());
            if (user == null)
                return null;

            return Json(user, JsonRequestBehavior.AllowGet);
        }
    }
}

DeltaDashboard/Controllers/RepresentativeController.cs
using DeltaDashboard.Models;
using DeltaDashboardBL.Manager;
using DeltaDashboardCommon.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeIsMoney.Helpers;

namespace DeltaDashboard.Controllers
{
    [Authorization]
    public class RepresentativeController : Controller
    {
        // GET: IndividualRep
        public ActionResult VendorRepSummary()
        {
            return View();
        }

        public ActionResult RepresentativeVendorRef()
        {
            return View();
        }

        public JsonResult GetVendorRepRef()
        {
            return Json(new DeltaLogedManager().GetVendorRepRef("", "").OrderBy(o => o.APRepName), JsonRequestBehavior.AllowGet);
        }
        public ActionResult IndividualRepDetail()
        {
            return View();
        }

        public JsonResult GetGridData(string APRepId)
        {
            var Data = new DeltaLogedManager().GetIndividualRep(APRepId);           
            return Json(Data, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetVendorRepSummary()
        {
            var vendorRepSummaryModel = new DeltaLogedManager().GetVendorRepSummary().OrderBy(o => o.APRepName);           

            return Json(vendorRepSummaryModel, JsonRequestBehavior.AllowGet);
        }

        private string ShiftName(string ShiftId)
        {
            string ShiftName = string.Empty;
            switch (ShiftId)
            {
                case "1":
                    ShiftName = "Regular";
                    break;
                case "2":
                    ShiftName = "Night";
                    break;
                default:
                    break;
            }
            return ShiftName;
        }
    }
}

DeltaDashboard/Views/Shared/CompleteAPRep.cshtml
<style type="text/css">
    .grid {
        width: 60%;
        height: 400px;
    }
</style>

<div>
    <div ui-grid="gridOptionsComplete" ui-grid-pagination ui-grid-selection class="grid"></div>
</div>

DeltaDashboard/Views/Shared/PendingAPRep.cshtml
<style type="text/css">
    .grid {
        width: 60%;        
    }
    
</style>

<div>
    <div ui-grid="gridOptionsPending" style="height: 444px;" ui-grid-pagination ui-grid-selection class="grid"></div>
</div>

DeltaDashboard/Views/Shared/SessionExpire.cshtml
@{
    Layout = null;
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
@*<script src="~/Scripts/angular.min.js"></script>
<script src="~/Scripts/angular-ui/ui-bootstrap-tpls.min.js"></script>*@

<style>
    .modal-header {
        background-color: #d9534f !important;
        color: white;
    }

    .modal-content {
        width: 598.988636px !important;
        height: 179.988636px !important;
    }
</style>
<body>
    <div>
        <!-- This html would live at the path specified in the controller: path/to/your/modal-template.html -->

        <div>
            <Center>
                @*<span class="text-danger">  Session Expired - Please login again...</span><br />
                    @Html.ActionLink("Login Again", "/Login")*@
            </Center>
        </div>


    </div>
</body>

DeltaDashboard/Views/Shared/_CommonDataLogHeader.cshtml
<script>
    function CommonDataLogController($rootScope, $scope, $http, $location) {



             var datafor = "";
            var url = $location.absUrl().split('?')[0]
            //get index of last forworded slash to get current page
            var IndexofLastSlash = url.lastIndexOf('/');
            var routeLink = url.substring(IndexofLastSlash + 1);
        if (routeLink == "CreditHold") {
            datafor = "Credit Hold"
        }
        else if (routeLink == "Escalation") {
            datafor = "Escalation"

        }
        else if (routeLink == "StatementReceipt") {
            datafor = "Statement Receipt"

        }
              var parameters = {
                  APRep: "",
                DataFor:datafor
                 }

            $http.post("@Url.Action("GetGridDataByAPRep", "CreditHold")", parameters).then(function (Result) {
            if (Result.data) {
                $rootScope.gridOptions.data = Result.data;
            }
        });




        $http.post("@Url.Action("GetAPRepUsersList", "CreditHold")").then(function (Result) {
            if (Result.data) {
                $scope.APRepUsersList = Result.data;
            }
        });




        $scope.setVendorValue = function () {
            if ($scope.VendorId != undefined)
                document.getElementById("HinddenVendorId").value = $scope.VendorId;
            else {
                document.getElementById("HinddenVendorId").value = document.getElementById("OrignalHinddenVendorId").value;
            }
        }

        $scope.GetVendorList = function () {
              $http.post("@Url.Action("GetAPUserData", "CreditHold")" + "?APRepId=" + $scope.APRep).then(function (Result) {
                    if (Result.data) {
                        $("#ShiftId").val(Result.data.ShiftId);
                        $("#ShiftName").val(Result.data.ShiftName);
                        $("#PODId").val(Result.data.PODId);
                        $("#PODName").val(Result.data.PODName);
                        $("#SupervisorId").val(Result.data.SupervisorId);
                        $("#SupervisorName").val(Result.data.SupervisorName);
                    }
                });

            $http.post("@Url.Action("GetVendorList", "CreditHold")" + "?APRepId=" + $scope.APRep).then(function (Result) {
                if (Result.data) {
                    $rootScope.VendorList = Result.data;
                }
            });

            var datafor = "";
            var url = $location.absUrl().split('?')[0]
            //get index of last forworded slash to get current page
            var IndexofLastSlash = url.lastIndexOf('/');
            var routeLink = url.substring(IndexofLastSlash + 1);
            if (routeLink == "CreditHold") {
                datafor ="Credit Hold"
            } else if (routeLink == "Escalation") {
                datafor = "Escalation"

            }
            else if (routeLink == "StatementReceipt") {
                datafor = "Statement Receipt"

            }
              var parameters = {
                  APRep: $scope.APRep,
                DataFor:datafor
                 }

            $http.post("@Url.Action("GetGridDataByAPRep", "CreditHold")", parameters).then(function (Result) {
            if (Result.data) {
                $rootScope.gridOptions.data = Result.data;
            }
        });

         }
    }

    DeltaApp.controller("CommonDataLogController", CommonDataLogController);
</script>
<input type="hidden" id="HinddenVendorId" />
<input type="hidden" id="OrignalHinddenVendorId" />
<input type="hidden" name="Id" id="DeltaLogId" />
<div ng-controller="CommonDataLogController">
    <div class="row">
        <div class="col-md-6 rightbuffer">
            <div class="row">AP Rep</div>
            <div class="row top-buffer">
                <select class="form-control" ng-model="APRep" ng-change="GetVendorList()" id="APRepId" required name="APRepId">
                    <option value="" selected>- Select AP Representative -</option>
                    <option ng-repeat="List in APRepUsersList" value="{{List.Id}}">{{List.FullName}}</option>
                </select>
            </div>
        </div>
        <div class="col-md-6 rightbuffer">
            <div class="row">Vendor Name</div>
            <div class="row top-buffer">
                <select class="form-control" ng-model="VendorId" required name="VendorId" Id="VendorId" ng-change="setVendorValue()">
                    <option value="" selected>- Select Vendor -</option>
                    <option ng-repeat="List in VendorList" value="{{List.Id}}">{{List.VendorName}}</option>
                </select>
            </div>
        </div>
    </div>

    <div class="row top-buffer">
        <div class="col-md-6 rightbuffer">
            <div class="row">Shift</div>
            <div class="row top-buffer">
                <input type="hidden" class="form-control" required name="ShiftId" Id="ShiftId" />
                <input type="text" class="form-control" required name="ShiftName" Id="ShiftName" disabled />
            </div>
        </div>
        <div class="col-md-6 rightbuffer">
            <div class="row">POD</div>
            <div class="row top-buffer">
                <input type="hidden" class="form-control" required name="PODId" Id="PODId" />
                <input type="text" class="form-control" required name="PODName" Id="PODName" disabled />
            </div>
        </div>
    </div>

    <div class="row top-buffer">
        <div class="col-md-6 rightbuffer">
            <div class="row">Supervisor Name</div>
            <div class="row top-buffer">
                <input type="hidden" class="form-control" required name="SupervisorId" Id="SupervisorId" />
                <input type="text" class="form-control" required name="SupervisorName" Id="SupervisorName" disabled />
            </div>
        </div>
    </div>
</div>

DeltaDashboard/Views/Shared/_ErrorPopup.cshtml
<!-- Modal -->
@*<link href="~/Content/Model.css" rel="stylesheet" />*@

<div modal="showModal" close="cancel()">
    <div class="modal-header"> <span style="font-size: 23px;">Error</span></div>
<div class="modal-body">
    <p>
        <span class="text-danger">
        </span>
    </p>
</div>
<div class="modal-footer">
        <button class="btnPriStandard" data-dismiss="modal" autofocus>Close</button>
</div>
</div>

DeltaDashboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delta - @ViewBag.Title </title>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/jquery-ui.min.js"></script>
    <link rel="stylesheet" type="text/css" media="screen" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/themes/base/jquery-ui.css">

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/AngularJs")

    <script src="~/Scripts/angular-animate.js"></script>
    <script src="~/Scripts/angular-sanitize.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
    @*<script src="https://ui-grid.info/release/ui-grid.js"></script>

        <link rel="stylesheet" href="https://ui-grid.info/release/ui-grid.css" type="text/css">*@

    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-grid/4.0.6/ui-grid.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-grid/4.0.6/ui-grid.css" type="text/css">
    <script src="~/Scripts/angular-route.js"></script>
    <script src="~/Scripts/angular-ui/ui-bootstrap.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <link href="~/Content/Layout.css" rel="stylesheet" />
    <link href="~/Content/ToastMessage.css" rel="stylesheet" />

    <script>
        //Top Navigation controller
        function NavigationController($scope, $location) {
            //get current url
            var url = $location.absUrl().split('?')[0]
            //get index of last forworded slash to get current page
            var IndexofLastSlash = url.lastIndexOf('/');
            var routeLink = url.substring(IndexofLastSlash + 1);

            //function to Active selected link
            $scope.isActive = function (SelectedLink) {

                if (routeLink == SelectedLink) {
                    return true
                }
                else {
                    return false
                }
            }

            $scope.isStatementReceipt = function () {
                if (routeLink == "StatementReceipt") {
                    return true;
                }
                else {
                    return false;
                }
            }

            $scope.isCreditHold = function () {
                if (routeLink == "CreditHold") {
                    return true;
                }
                else {
                    return false;
                }
            }

            $scope.isEscalation = function () {
                if (routeLink == "Escalation") {
                    return true;
                }
                else {
                    return false;
                }
            }

            $scope.isVerification = function () {
                if (routeLink == "Verification") {
                    return true;
                }
                else {
                    return false;
                }
            }


            $scope.isDeltaDashboard = function () {
                if (routeLink == "Index" || routeLink == "VendorRepSummary" || routeLink == "EscalationStatus" || routeLink == "CreditHoldStatus" || routeLink == "IndividualRepDetail" || routeLink == "EscalationHistory" || routeLink == "CreditHoldHistory") {
                    return true;
                }
                else {



                    return false;
                }
            }



        }

        var DeltaApp = angular.module("DeltaApp", ["ui.grid", "ui.grid.pagination", "ui.grid.selection"]);

        DeltaApp.controller("NavigationController", NavigationController);

        DeltaApp.directive('showFocus', function ($timeout) {
            return function (scope, element, attrs) {
                scope.$watch(attrs.showFocus,
                    function (newValue) {
                        $timeout(function () {
                            newValue && element[0].focus();
                        });
                    }, true);
            }
        });

        DeltaApp.directive('compile', function ($compile) {
            return function (scope, element, attrs) {
                scope.$watch(
                    function (scope) {
                        // watch the 'compile' expression for changes
                        return scope.$eval(attrs.compile);
                    },
                    function (value) {
                        // when the 'compile' expression changes assign it into the current DOM
                        element.html(value);

                        // compile the new DOM and link it to the current scope.
                        // NOTE: we only compile .childNodes so that we don't get into infinite loop compiling ourselves
                        $compile(element.contents())(scope);
                    }
                );
            }
        });
    </script>
</head>
<body id="mask1" class="custombody" ng-app="DeltaApp">
    <div ng-cloak>
        <div class="fullcontent">
            <header>
                @Html.Partial("_topNavigation")
            </header>

            <div class="body-content mainContainer">
                @RenderBody()
            </div>
        </div>
        <footer>
            @Html.Partial("_bottomNavigation")
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)      

        <script>
            var JQuery = $.noConflict();

            var height = JQuery(document).height() - 133;

            JQuery('.fullcontent').css('min-height', height + 'px'); 

        </script>
    </div>
</body>
</html>

DeltaDashboard/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">
    <title>@ViewBag.Title </title>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")   

    @*<link href="~/Content/Layout.css" rel="stylesheet" />
    <link href="~/Content/Login.css" rel="stylesheet" />
    <link href="~/Content/ToastMessage.css" rel="stylesheet" />*@
    <style>
        .responsiveImg {
            margin-top: 10px;
            width: 100%;
            max-width: 205px;
            height: auto;
            margin-left: 90px;
        }
    </style>
    
</head>
<body class="custombody">
    <div class="fullcontent">
        <header>
            <div class="row">
                <div class="topbar logintopbar">
                    <div class="col-md-4"></div>
                    <div class="col-md-6"><a href="#"><img src="~/Content/Images/Logo.png" /></a></div>
                </div>
            </div>
            <div class="row" style="margin-top:5%">
                <div class="topbar logintopbar" style="background-color: #f9f9f9;">
                    <div class="col-md-4"></div>
                    <div class="col-md-6"><a href="#"><img src="~/Content/Images/Delta logo.png" class="responsiveImg" /> </a></div>
                </div>
            </div>
        </header>

    <div class="body-content mainContainer">
        @RenderBody()
    </div>
    </div>

    <footer>
        @Html.Partial("_bottomNavigation")
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        var JQuery = $.noConflict();

        var height = JQuery(document).height() - 133;

        JQuery('.fullcontent').css('min-height', height + 'px');
    </script>

</body>
</html>

DeltaDashboard/Views/Shared/_bottomNavigation.cshtml
<div class="footer-bottom">
    <div class="">
        <div class="row footermargin">

            @*<div class="col-md-4 bottomrowsize footerPossition">
                <div class="copyright">
                    <img src="~/Content/Images/shield.svg" alt="NeBraska" />
                    <span> © @System.DateTime.Now.Year @Common.Helpers.ResourceStrings.FooterText</span>
                </div>
            </div>

            <div class="col-md-3 bottomrowsize">
                <div id="EasyLink">
                    @Common.Helpers.ResourceStrings.EasyLinkText  <span id="EasyLinkNo">@Common.Helpers.ResourceStrings.EasyLinkNumberText  </span>
                </div>
            </div>

            <div class="col-md-3 bottomrowsize">
                <div class="contact">
                    <img src="~/Content/Images/envelope.svg" alt="Email:" /> <a href="mailto:orderbooks@nebook.com">@Common.Helpers.ResourceStrings.NEBookEmailText </a>
                </div>
            </div>

            <div class="col-md-2 bottomrowsize">
                <div class="contact">
                     <img src="~/Content/Images/phone.svg" alt="Phone:" /> <span>  @Common.Helpers.ResourceStrings.NEPhoneNumberText  </span>
                </div>
            </div>*@

            <div class="row">
                <div class="col-md-4">
                    <div class="copyright">
                        <img src="~/Content/Images/footerlogo.png" alt="Integrative" height="30" />
                        <span> Copyright © 2018 Integrative Systems, Inc. </span>
                    </div>
                </div>
                <div class="col-md-4 SupportLinksblock">
                    @*<div class="row">
                        <div class="col-md-12">
                            Integrative Company Links:
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 SupportLinks OrderSupplies" >
                            <a href="https://supplies.nebook.com/">Daily Task</a>
                        </div>
                        <div class="col-md-6 SupportLinks">
                            <a href="http://support.nebook.com">IT Support </a>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 SupportLinks CollageStoreDesign" >
                            <a href="http://nebook.com/services/#CollegeStore">TimeSheet Design</a>
                        </div>
                        <div class="col-md-6 SupportLinks">
                            <a href=" http://nebook.com/spectrum/">Spectrum</a>
                        </div>
                    </div>*@

                </div>
                <div class="col-md-4 pull-right rightsidelinks">
                    @*<div id="EasyLink">
                         <span id="EasyLinkNo">  </span>
                    </div>
                    <div class="contact">
                        <img src="~/Content/Images/envelope.svg" alt="Email:" /> <a href="mailto:orderbooks@nebook.com"> abc </a>
                    </div>
                    <div class="contact">
                        <img src="~/Content/Images/phone.svg" alt="Phone:" /> <span> abc  </span>
                    </div>*@
                </div>
            </div>
            @*<div class="row">
                <div class="col-md-4">

                </div>
                <div class="col-md-4">

                </div>
                <div class="col-md-4">

                </div>
            </div>
            <div class="row">
                <div class="col-md-4">

                </div>
                <div class="col-md-4">

                </div>
                <div class="col-md-4">

                </div>
            </div>*@
        </div>
    </div>
</div>

DeltaDashboard/Views/Shared/_topNavigation.cshtml
<style>
    .responsiveImg {
        margin-top: 10px;
        width: 100%;
        max-width: 205px;
        height: auto;
    }

    .responsiveClientImg {
        margin-top: 10px;       
        max-width: 250px;
        height: auto;
    }
    .table {
        border: 1px solid #ccc;
    }
        .table thead {
            background-color: #8adffd;
        }

    .yourlogo {
        height: 150px;
        margin-top: -12px;
        width: 165px;
    }

</style>

<div class="topbar">
    <div class="col-md-9">
        <div class="col-md-6">
            <a href="#"><img src="~/Content/Images/Delta logo.png" class="responsiveImg"  style="margin-bottom:10px" /> </a>
        </div>
        <div class="col-md-6">

            @{ if (Session["UserName"].ToString() == "demouser")
                {

                    <a href="#"><img src="~/Content/Images/Your logo here.bmp" style="margin-bottom:10px" class="responsiveImg yourlogo" /> </a>
                }
                else
                {

            <a href="#"><img src="~/Content/Images/ClientLogo/FollettLogo.jpg" style="margin-bottom:10px" class="responsiveImg" /> </a>
                    } }

        </div>
    </div>
    <div class="col-md-3 topbarright top-buffer">
        <span> </span>
        <span class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <span class="topbarmenu">Welcome @Session["FullName"]</span>
            </a>  
            @*@{ if (Session["Role"].ToString() == "4" || Session["Role"].ToString() == "3" || Session["Role"].ToString() == "5")
                {
            <span class="caret topbarmenu"></span>
            <ul class="dropdown-menu topbardropdown">
                <li class="topbarList"><a href="~/Vendor/ManageVendor">Vendor Management</a></li>
                <li class="topbarList"><a href="~/User/ManageUser">User Management</a></li>
                
                
            </ul> 
                }
                }*@
        </span>
        <span id="logout"><a href="@Url.Action("LogOff", "Account")" class="topbarmenu">Log Out</a></span>
    </div>
</div>

<nav ng:controller="NavigationController">
    <div class="container-fluid topmenus">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle glyphicon glyphicon-menu-hamburger menucolapusbutton" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right topLink">
                @*<li ng-class="{active:{{isVendoRep()}}}">
            <a class="Navigation" ng-class="{ active:{{isVendoRep()}}}" href="@Url.Action("VendorRepSummary", "Representative")">Vendor Rep Summary</a>
        </li>
        <li ng-class="{active:{{isIndividual()}}}">
            <a class="Navigation" ng-class="{ active:{{isIndividual()}}}" href="@Url.Action("IndividualRepDetail", "Representative")">Individual Rep Detail</a>
        </li>
        <li ng-class="{active:{{isCHStatus()}}}">
            <a class="Navigation" ng-class="{ active:{{isCHStatus()}}}" href="@Url.Action("CreditHoldStatus", "CreditHold")">Credit Hold Status</a>
        </li>
        <li ng-class="{active:{{isCSHistory()}}}">
            <a class="Navigation" ng-class="{ active:{{isCSHistory()}}}" href="@Url.Action("CreditHoldHistory", "CreditHold")">Credit Hold History</a>
        </li>
        <li ng-class="{active:{{isEStatus()}}}">
            <a class="Navigation" ng-class="{ active:{{isEStatus()}}}" href="@Url.Action("EscalationStatus", "Escalation")">Escalation Status</a>
        </li>
        <li ng-class="{active:{{isEHistory()}}}">
            <a class="Navigation" ng-class="{ active:{{isEHistory()}}}" href="@Url.Action("EscalationHistory", "Escalation")">Escalation History</a>
        </li>
        <li ng-class="{active:{{isVerification()}}}">
            <a class="Navigation" ng-class="{ active:{{isVerification()}}}" href="@Url.Action("Index", "Verification")">Verification</a>
        </li>*@
                <li ng-class="{active:{{isDeltaDashboard()}}}">
                    <a class="Navigation" ng-class="{ active:{{isDeltaDashboard()}}}" href="@Url.Action("Index", "DeltaDashboard")">Dashboard</a>
                </li>
                <li ng-class="{active:{{isCreditHold()}}}">
                    <a class="Navigation" ng-class="{ active:{{isCreditHold()}}}" href="@Url.Action("CreditHold", "CreditHold")">Credit Hold</a>
                </li>
                <li ng-class="{active:{{isEscalation()}}}">
                    <a class="Navigation" ng-class="{ active:{{isEscalation()}}}" href="@Url.Action("Escalation", "Escalation")">Escalation</a>
                </li>

                <li ng-class="{active:{{isStatementReceipt()}}}">
                    <a class="Navigation" ng-class="{ active:{{isStatementReceipt()}}}" href="@Url.Action("StatementReceipt", "StatementReceipts")">Statement Receipt</a>
                </li>
                @*@{ if (Session["Role"].ToString() == "4" || Session["Role"].ToString() == "3" || Session["Role"].ToString() == "5")
                    {*@
            <li ng-class="{active:{{isVerification()}}}">
                <a class="Navigation" ng-class="{ active:{{isVerification()}}}" href="@Url.Action("Verification", "Verification")">Verification</a>
            </li>
                        @*}
                    }*@
            </ul>
        </div>
    </div>
</nav>