DeltaDashboard/Controllers/DeltaDashboardController.cs
using DeltaDashboardBL.Manager;
using DeltaDashboardCommon.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeIsMoney.Helpers;

namespace DeltaDashboard.Controllers
{
    [Authorization]
    public class DeltaDashboardController : Controller
    {
        // GET: DeltaDashboard
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult DeltaIndex()
        {
            User user = new UserManager().GetUserByUserName(Session["UserName"].ToString());
            if (user == null)
                return null;

            return Json(user, JsonRequestBehavior.AllowGet);
        }
    }
}

DeltaDashboard/Controllers/ExportController.cs
using ClosedXML.Excel;
using ClosedXML.Excel.Drawings;
using DeltaDashboard.Helper;
using DeltaDashboardBL.Manager;
using DeltaDashboardCommon.Domain;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using TimeIsMoney.Helpers;

namespace DeltaDashboard.Controllers
{
    [Authorization]
    public class ExportController : Controller
    {
        // GET: Export
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetGridData(string logtype, string status, int userId, bool IsAdmin = true, string logtypeName = "", string statusName = "", string userName = "")
        {

            List<DeltaLoged> ExportData = new DeltaLogedManager().GetExportDataDeltaLogByUser(logtype, status, userId, IsAdmin).OrderBy(o => o.APRepName).ToList();

            ExcelParaModel objExcelParaModel = new ExcelParaModel();
            objExcelParaModel.Logtype = logtypeName == "Statement Receipt" ? "Statement" : logtypeName;
            objExcelParaModel.UserName = userName;
            objExcelParaModel.Status = statusName;
            TempData["ExcelParaModel"] = objExcelParaModel;
            TempData["ExportToExcelReport"] = ExportData;

            return Json(ExportData, JsonRequestBehavior.AllowGet);
        }

        public FileResult ExportToExcel()
        {
            if (TempData["ExportToExcelReport"] != null)
            {
                List<DeltaLoged> ExportToExcelReport = (List<DeltaLoged>)TempData["ExportToExcelReport"];
                TempData["ExportToExcelReport"] = ExportToExcelReport;
                var objExcelParaModel = TempData["ExcelParaModel"] != null ? (ExcelParaModel)TempData["ExcelParaModel"] : null;
                TempData["ExcelParaModel"] = objExcelParaModel;

                DataTable tblExportToExcel = GetExportData(ExportHelper.GetExportDataTable(new DataTable("Delta Dashboard Data")), ExportToExcelReport);
                XLExporter vksxl = new XLExporter();

                using (XLWorkbook wb = vksxl.Export2Excel("Delta Dashboard Data Download", XLColor.White, XLColor.Black, 15, true, objExcelParaModel.Status != null ? objExcelParaModel.Status : "All",
                objExcelParaModel.Logtype != null ? objExcelParaModel.Logtype : "", objExcelParaModel.UserName != null ? objExcelParaModel.UserName : "",
                XLColor.White, XLColor.Black, 10, tblExportToExcel, XLColor.Brown, XLColor.White, "Delta Dashboard Data", "DeltaDashboard_Data_Download.xlsx", null))
                {
                    string path = Server.MapPath("~/Content/Images/Delta logo.png");
                    byte[] imageByteData = System.IO.File.ReadAllBytes(path);
                    string imageBase64Data = Convert.ToBase64String(imageByteData);
                    string imageDataURL = string.Format("data:image/png;base64,{0}", imageBase64Data);

                    byte[] myByte = new byte[10];

                    MemoryStream theMemStream = new MemoryStream();

                    theMemStream.Write(imageByteData, 0, imageByteData.Length);


                    #region Png

                    var ws = wb.Worksheet("Delta Dashboard Data");

                    ws.AddPicture(theMemStream, XLPictureFormat.Png, "PngImage")
                            .MoveTo(ws.Cell("A2").Address).WithSize(200, 65);
                    // ws.Cell("A1").Value = Title;

                    #endregion Png

                    // wb.Worksheets.Add(tblExportToExcel).Tables.FirstOrDefault().ShowAutoFilter = false;
                    using (MemoryStream stream = new MemoryStream())
                    {
                        wb.SaveAs(stream);
                        return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Delta_Dashboard_Data_Download.xlsx");
                    }

                }
            }
            return null;

        }

        private DataTable GetExportData(DataTable dt, List<DeltaLoged> ExportToExcelReport)
        {
            foreach (var DeltaLoged in ExportToExcelReport)
            {
                dt.Rows.Add(DeltaLoged.StatusString, DeltaLoged.LogedDataFor == "Statement Receipt" ? "Statement" : DeltaLoged.LogedDataFor, DeltaLoged.DisplayCreatedDate, DeltaLoged.VendorName, DeltaLoged.VendorNumber, DeltaLoged.APRepName, DeltaLoged.PODName, DeltaLoged.SupervisorName, DeltaLoged.DisplayCreditHoldOn, DeltaLoged.DisplayCreditHoldOff, DeltaLoged.ReasonforCredithold, DeltaLoged.ReasonforEscalation, DeltaLoged.ActionPlanToPreventEscalation, DeltaLoged.DisplayStatementRequestedDate, DeltaLoged.DisplayStatementReceivedDate, DeltaLoged.DisplayStatementMatchCompleteDate);
            }

            return dt;
        }


        //public JsonResult ExportToExcel(string logtype, string status, int userId, bool IsAdmin = true)
        //{
        //    //  ExcelParaModel objExcelParaModel = new ExcelParaModel();

        //    var wb = new XLWorkbook();
        //    var ExportData= new DeltaLogedManager().GetExportDataDeltaLogByUser(logtype, status, userId, IsAdmin).OrderBy(o => o.APRepName).ToList();
        //    var dataTable = ToDataTable(ExportData);

        //    // Add a DataTable as a worksheet
        //    wb.Worksheets.Add(dataTable);       
        //   wb.SaveAs(Server.MapPath("/ExportedData/DeltaDashbord.xlsx"));
        //    return Json("~/ExportedData/DeltaDashbord.xlsx", JsonRequestBehavior.AllowGet);
        //}

        //public DataTable ToDataTable<T>(List<T> items)
        //{
        //    DataTable dataTable = new DataTable(typeof(T).Name);

        //    //Get all the properties
        //    PropertyInfo[] Props = typeof(T).GetProperties(BindingFlags.Public | BindingFlags.Instance);
        //    foreach (PropertyInfo prop in Props)
        //    {
        //        //Defining type of data column gives proper data table 
        //        var type = (prop.PropertyType.IsGenericType && prop.PropertyType.GetGenericTypeDefinition() == typeof(Nullable<>) ? Nullable.GetUnderlyingType(prop.PropertyType) : prop.PropertyType);
        //        //Setting column names as Property names
        //        dataTable.Columns.Add(prop.Name, type);
        //    }
        //    foreach (T item in items)
        //    {
        //        var values = new object[Props.Length];
        //        for (int i = 0; i < Props.Length; i++)
        //        {
        //            //inserting property values to datatable rows
        //            values[i] = Props[i].GetValue(item, null);
        //        }
        //        dataTable.Rows.Add(values);
        //    }
        //    //put a breakpoint here and check datatable
        //    return dataTable;
        //}

    }

    public class ExcelParaModel
    {
        public String Status { get; set; }

        public String Logtype { get; set; }

        public String UserName { get; set; }

    }
    public static class ExportHelper
    {
        public static DataTable GetExportDataTable(DataTable dt)
        {
            dt.Columns.AddRange(new DataColumn[1] { new DataColumn("Approved") });
            dt.Columns.AddRange(new DataColumn[1] { new DataColumn("Log Type") });
            dt.Columns.AddRange(new DataColumn[1] { new DataColumn("Date Log") });
            dt.Columns.AddRange(new DataColumn[1] { new DataColumn("Vendor Name") });
            dt.Columns.AddRange(new DataColumn[1] { new DataColumn("Vendor Number") });
            dt.Columns.AddRange(new DataColumn[1] { new DataColumn("APRep") });
            dt.Columns.AddRange(new DataColumn[1] { new DataColumn("POD") });
            dt.Columns.AddRange(new DataColumn[1] { new DataColumn("Supervisor Name") });
            dt.Columns.AddRange(new DataColumn[1] { new DataColumn("Credit On Hold") });
            dt.Columns.AddRange(new DataColumn[1] { new DataColumn("Credit Off Hold") });
            dt.Columns.AddRange(new DataColumn[1] { new DataColumn("Reason for Credit hold") });
            dt.Columns.AddRange(new DataColumn[1] { new DataColumn("Reason for Escalation") });
            dt.Columns.AddRange(new DataColumn[1] { new DataColumn("Action Plan To Prevent Escalation") });
            dt.Columns.AddRange(new DataColumn[1] { new DataColumn("Statement Requested Date") });
            dt.Columns.AddRange(new DataColumn[1] { new DataColumn("Statement Received Date") });
            dt.Columns.AddRange(new DataColumn[1] { new DataColumn("Statement Match Complete Date") });
            return dt;
        }

    }

}

DeltaDashboard/Controllers/RewardController.cs
using DeltaDashboardBL.Manager;
using DeltaDashboardCommon.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeIsMoney.Helpers;

namespace DeltaDashboard.Controllers
{
    [Authorization]
    public class RewardController : Controller
    {
        // GET: Reward
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetAPRepUsersList()
        {
            return Json(new UserManager().GetUserList().Where(o => o.Role != "5").ToList(), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetPODList()
        {
            UserManager userManager = new UserManager();
            var podList = userManager.GetPODList().ToList().Where(o => o.Name != "Maroon");
            List<POD> lstpod = new List<POD>();
            foreach(var varpod in podList)
            {
                POD pod = new POD();
                pod.Id = varpod.Id;
                pod.Name = varpod.Name;
                pod.FullName = varpod.FullName;
                lstpod.Add(pod);
            }
            return Json(lstpod, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetRewardList()
        {
            RewardManager rewardManager = new RewardManager();
            var rewradList = rewardManager.GetRewards().ToList().OrderByDescending(x => x.Id);
            List<Reward> rewards = new List<Reward>();
            foreach(var reward in rewradList)
            {
                Reward rwd = new Reward();
                rwd.Category = reward.Category;
                rwd.Comments = reward.Comments;
                rwd.RewardTo = reward.RewardTo;
                rwd.RewardDate = reward.RewardDate;
                rwd.RewardDateDisplay = reward.RewardDateDisplay;
                rewards.Add(rwd);
;
            }
            return Json(rewards, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Reward(Reward reward)
        {
            reward.CreatedBy = (int)Session["UserId"];
            reward.CreatedDate = DateTime.Now;
            if (reward.Id == 0)
                new RewardManager().CreateReward(reward);
            else
                new RewardManager().UpdateStatus(reward);

            return Json(reward);
        }
    }
}

DeltaDashboard/Controllers/UserController.cs
using DeltaDashboardBL.Manager;
using DeltaDashboardCommon.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeIsMoney.Helpers;
using TimeIsMoneyCommon.HelperClass;
using static TimeIsMoneyCommon.HelperClass.Enums;

namespace DeltaDashboard.Controllers
{
    [Authorization]
    public class UserController : Controller
    {
        // GET: ManageUser
        public ActionResult ManageUser()
        {
            return View();
        }

        [HttpPost]
        public JsonResult CreateUser(User user)
        {
            UserManager userManager = new UserManager();
            User userName = userManager.GetUserByUserName(user.UserName);
            if (userName == null)
            {
                userManager.CreateUser(user);

                UserVendorAssociationManager uvaManager = new UserVendorAssociationManager();
                User userNameInfo = userManager.GetUserByUserName(user.UserName);
                if (userNameInfo != null)
                {
                    UserVendorAssociation uvAssociation = new UserVendorAssociation(); 
                    foreach(var selectedVendor in user.SelectedVendor)
                    {
                        uvAssociation.VendorId = selectedVendor.Id;
                        uvAssociation.UserId = userNameInfo.Id;
                        uvaManager.CreateUVAssociation(uvAssociation);
                    }
                }
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            return Json(false, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult UpdateUser(User user)
        {
            try
            {
                user = new UserManager().UpdateUser(user);
                UserVendorAssociation uvAssociation = new UserVendorAssociation();
                UserVendorAssociationManager uvaManager = new UserVendorAssociationManager();

                List<UserVendorAssociation> associationVendor = new UserVendorAssociationManager().GetAssociationVendor(user.Id);
                if (associationVendor != null)
                    uvaManager.DeleteUVAssociatio(associationVendor);

                foreach (var selectedVendor in user.SelectedVendor)
                {
                    uvAssociation.VendorId = selectedVendor.Id;
                    uvAssociation.UserId = user.Id;
                    uvaManager.CreateUVAssociation(uvAssociation);
                }
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult GetSelectedVendor(string userId)
        {
            List<Vendor> selectedVendor = new UserVendorAssociationManager().GetSelectedVendor(Convert.ToInt32(userId));
            return Json(selectedVendor, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetUserList()
        {
            List<User> User = new UserManager().GetUserList().OrderBy(o => o.FullName).ToList();
            List<User> UserDt = User.Where(o => o.Role != Convert.ToString((int)Role.Admin)).ToList();
            List<User> UserDetails = new List<User>();
            foreach (User user in UserDt) {
                User userObj = new User();
                userObj.Id = user.Id;
                userObj.FullName = user.FullName;
                userObj.UserName = user.UserName;
                userObj.EmailId = user.EmailId;
                userObj.Password = user.Password;
                userObj.Role = user.Role;
                userObj.RoleName = RoleName(user.Role);
                userObj.ShiftId = user.ShiftId;
                userObj.PodId = user.PodId;
                userObj.SupervisorId = user.SupervisorId;
                userObj.isDeltaTeam = user.isDeltaTeam;
                UserDetails.Add(userObj);
            }
            return Json(UserDetails, JsonRequestBehavior.AllowGet);
        }

        private string RoleName(string role)
        {
            string RoleName = string.Empty;
            switch (role)
            {
                case "1":
                    RoleName = "AP Representative";
                    break;
                case "2":
                    RoleName = "POD Lead";
                    break;
                case "3":
                    RoleName = "Team Lead";
                    break;
                case "4":
                    RoleName = "Supervisor";
                    break;
                case "6":
                    RoleName = "Data Processing";
                    break;
                default:
                    break;
            }
            return RoleName;
        }

        public JsonResult GetNonAlphaVendorList()
        {
            List<Vendor> UserDetails = new UserManager().GetVendorList();
            List<Vendor> alphaVendor = UserDetails.Where(o => o.VendorName.Contains("Alpha")).ToList();
            List<Vendor> nonAlphaVendor = UserDetails.Except(alphaVendor).ToList();
            return Json(nonAlphaVendor, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAlphaVendorList()
        {
            List<Vendor> UserDetails = new UserManager().GetVendorList();
            List<Vendor> alphaVendor = UserDetails.Where(o => o.VendorName.Contains("Alpha")).ToList();
            return Json(alphaVendor, JsonRequestBehavior.AllowGet);
        }
    }
}

DeltaDashboard/Views/DeltaDashboard/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    @@media (min-width: 992px) {
        .col-md-2 {
            width: 12.666667%;
        }
    }
</style>
<script>
    function DeltaDashController($rootScope, $scope, $http) {
          @*$http.post("@Url.Action("DeltaIndex", "DeltaDashboard")").then(function (Result) {
              if (Result.data) {
                  if (Result.data.isDeltaTeam) {
                      document.getElementById("dvTabSharedDrive").style.display = "block";
                  } else {
                      document.getElementById("dvTabSharedDrive").style.display = "none";
                  }
              }
        });*@
    }
    DeltaApp.controller("DeltaDashController", DeltaDashController);
</script>

<div ng-controller="DeltaDashController">
    <div class="row Header" style="margin-left:0">
        <h2 class="Title">Welcome To Delta Dashboard</h2>
    </div>
    <div class="top-buffer">
        <div class="row">
            <div class="col-md-3 Box">
                <a href="@Url.Action("VendorRepSummary", "Representative")" class="textdecoration">
                    <div class="col-md-12 Orderbox">
                        <h2>Vendor Representative Summary</h2>
                    </div>
                </a>
            </div>
            <div class="col-md-3 Box">
                <a href="@Url.Action("IndividualRepDetail", "Representative")" class="textdecoration">
                    <div class="col-md-12 OrderboxRow">
                        <h2>Vendor Representative Detail </h2>
                    </div>
                </a>
            </div>
            <div class="col-md-3 Box">
                <a href="@Url.Action("CreditHoldStatus", "CreditHold")" class="textdecoration">
                    <div class="col-md-12 Orderbox">
                        <h2>Credit Hold Status</h2>
                    </div>
                </a>
            </div>
            <div class="col-md-3 Box">
                <a href="@Url.Action("CreditHoldHistory", "CreditHold")" class="textdecoration">
                    <div class="col-md-12 OrderboxRow">
                        <h2>Credit Hold History</h2>
                    </div>
                </a>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3 Box">
                <a href="@Url.Action("ManageUser", "User")" class="textdecoration">
                    <div class="col-md-12 Orderbox">
                        <h2>
                            Delta  <br />Vendor Representative Management
                        </h2>
                    </div>
                </a>
            </div>
            <div class="col-md-3 Box">
                <a href="@Url.Action("RepresentativeVendorRef", "Representative")" class="textdecoration">
                    <div class="col-md-12 OrderboxRow">
                        <h2>
                            Vendor Representative/Vendor X-ref
                        </h2>
                    </div>
                </a>
            </div>
            <div class="col-md-3 Box">
                <a href="@Url.Action("EscalationStatus", "Escalation")" class="textdecoration">
                    <div class="col-md-12 Orderbox">
                        <h2>Escalation Status</h2>
                    </div>
                </a>
            </div>
            <div class="col-md-3 Box">
                <a href="@Url.Action("EscalationHistory", "Escalation")" class="textdecoration">
                    <div class="col-md-12 OrderboxRow">
                        <h2>Escalation History</h2>
                    </div>
                </a>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3 Box">
                <a href="@Url.Action("Index", "ClientFeedback")" class="textdecoration">
                    <div class="col-md-12 Orderbox">
                        <h2>
                            Feedback for <br /> Delta Team
                        </h2>
                    </div>
                </a>
            </div>
            <div class="col-md-3 Box">
                <a href="@Url.Action("DataProcessing", "DataProcessing")" class="textdecoration">
                    <div class="col-md-12 OrderboxRow">
                        <h2>
                            Feedback for <br /> Data Processing
                        </h2>
                    </div>
                </a>
            </div>
            @{ if (Session["Role"].ToString() == "4" || Session["Role"].ToString() == "3" || Session["Role"].ToString() == "5")
                {
                    <div class="col-md-3 Box">
                        <a href="@Url.Action("ManageVendor", "Vendor")" class="textdecoration">
                            <div class="col-md-12 Orderbox">
                                <h2>
                                    Vendor Management
                                </h2>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-3 Box">
                        <a href="@Url.Action("Index", "Export")" class="textdecoration">
                            <div class="col-md-12 OrderboxRow">
                                <h2>
                                    Export
                                </h2>
                            </div>
                        </a>
                    </div>

                    @*Added by Shraddha on 15-Jun-2022 *@
                    <div class="row" style="margin-inline:auto;">
                        <div class="col-md-3 Box">
                            <a href="@Url.Action("Index", "Reward")" class="textdecoration">
                                <div class="col-md-12 Orderbox">
                                    <h2>
                                        Reward
                                    </h2>
                                </div>
                            </a>
                        </div>
                    </div>
                }
                else
                {
                    <div class="col-md-3 Box">
                        <a href="@Url.Action("Index", "Export")" class="textdecoration">
                            <div class="col-md-12 Orderbox">
                                <h2>
                                    Export
                                </h2>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-3 Box">
                        <a href="@Url.Action("Index", "Reward")" class="textdecoration">
                            <div class="col-md-12 OrderboxRow">
                                <h2>
                                    Reward
                                </h2>
                            </div>
                        </a>
                    </div>
                }
            }
        </div>
            <br /><br /><br />
        </div>
</div>